package com.palmatolay.innodoxhomework.model;

import javax.persistence.*;

/**
 * Simple POJO to describe an account in the database.
 * Long id: generated by the database sequence during a new record save
 * String username: Have to be unique and not nullable, otherwise the new record will be rejected
 * String email: Have to be unique and not nullable, otherwise the new record will be rejected
 */
@Entity
public class Account  {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@Column(nullable = false, unique = true)
	private String username;

	@Column(nullable = false, unique = true)
	private String email;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}
