package com.palmatolay.innodoxhomework.model;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import javax.persistence.*;

/**
 * Simple POJO to describe an account in the database.
 * Long id: generated by the database sequence during a new record save
 * String name: Have to be not nullable, otherwise the new record will be rejected
 * Account owner: it will be an id in the database what refer the product owner
 * (If the owner is deleted from the database all the products will be also deleted what refer to the that account)
 */
@Entity
public class Product {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@Column(nullable = false)
	private String name;

	@ManyToOne(fetch = FetchType.LAZY)
	@OnDelete(action = OnDeleteAction.CASCADE)
	@JoinColumn(name = "OWNER_ID")
	private Account owner;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Account getOwner() {
		return owner;
	}

	public void setOwner(Account owner) {
		this.owner = owner;
	}
}
